// <auto-generated />
using System;
using BTCPayServer.Plugins.ChapSmart;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.ChapSmart.Data.Migrations
{
    [DbContext(typeof(ChapSmartDbContext))]
    partial class ChapSmartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.ChapSmart")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .UseIdentityByDefaultColumns();

            modelBuilder.Entity("BTCPayServer.Plugins.ChapSmart.Data.ChapSmartPayout", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<decimal>("AmountBTC")
                    .HasColumnType("numeric");

                b.Property<decimal>("AmountTZS")
                    .HasColumnType("numeric");

                b.Property<DateTimeOffset?>("CompletedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ErrorMessage")
                    .HasColumnType("text");

                b.Property<string>("InvoiceId")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("RecipientName")
                    .HasColumnType("text");

                b.Property<string>("ResponseData")
                    .HasColumnType("text");

                b.Property<int>("RetryCount")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0);

                b.Property<string>("PaymentProviderTransId")
                    .HasColumnType("text");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("StoreId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("PK_Payouts");

                b.HasIndex("CreatedAt");

                b.HasIndex("InvoiceId");

                b.HasIndex("Status");

                b.HasIndex("StoreId");

                b.ToTable("Payouts", "BTCPayServer.Plugins.ChapSmart");
            });
#pragma warning restore 612, 618
        }
    }
}
